// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GetUserLevelDetailsProcedure from "../get_user_level_details_procedure";
import * as GetUserLevelRunsProcedure from "../get_user_level_runs_procedure";
import * as GetUsersOverviewProcedure from "../get_users_overview_procedure";

export type GetUserLevelDetailsArgs = __Infer<typeof GetUserLevelDetailsProcedure.params>;
export type GetUserLevelDetailsResult = __Infer<typeof GetUserLevelDetailsProcedure.returnType>;
export type GetUserLevelRunsArgs = __Infer<typeof GetUserLevelRunsProcedure.params>;
export type GetUserLevelRunsResult = __Infer<typeof GetUserLevelRunsProcedure.returnType>;
export type GetUsersOverviewArgs = __Infer<typeof GetUsersOverviewProcedure.params>;
export type GetUsersOverviewResult = __Infer<typeof GetUsersOverviewProcedure.returnType>;

