// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  timeLimitSeconds: __t.u32().name("time_limit_seconds"),
  verbsPerLevel: __t.u32().name("verbs_per_level"),
  activeVerbCategory: __t.u32().name("active_verb_category"),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.identity().name("updated_by"),
});
