// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userIdentity: __t.identity().name("user_identity"),
  levelAttempted: __t.u32().name("level_attempted"),
  errorsCount: __t.u32().name("errors_count"),
  durationSeconds: __t.u32().name("duration_seconds"),
  completedAt: __t.timestamp().name("completed_at"),
  isPerfectRun: __t.bool().name("is_perfect_run"),
  clientTimestampStart: __t.timestamp().name("client_timestamp_start"),
  clientTimestampEnd: __t.timestamp().name("client_timestamp_end"),
});
