// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  usernameLower: __t.string().name("username_lower"),
  username: __t.string(),
  passwordHash: __t.string().name("password_hash"),
  role: __t.string(),
  currentLevelCap: __t.u32().name("current_level_cap"),
  createdAt: __t.timestamp().name("created_at"),
});
