// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  levelGroup: __t.u32().name("level_group"),
  category: __t.u32(),
  infinitive: __t.string(),
  pastSimple: __t.string().name("past_simple"),
  pastParticiple: __t.string().name("past_participle"),
  active: __t.bool(),
});
